# sintassi ruby

Vagrant.configure("2") do |config|

  config.vm.provision "shell", inline: "echo starting machine configuration"
  
  #Configurazione JenkinsVM; provisioning by shell mediante script jenkins.sh
  config.vm.define "JenkinsVM" do |jenkins|
    jenkins.vm.box_check_update = false
    jenkins.vm.box = "ubuntu/xenial64"
    jenkins.vm.network "forwarded_port", guest: 102, host: 1020
    jenkins.vm.network "private_network", ip: "192.168.90.20"
    jenkins.vm.provision "shell", path: "jenkins.sh"
    jenkins.vm.provider "virtualbox" do |vb1|
	vb1.name = "JenkinsVM"
	vb2.memory = 2048
    	vb2.cpus = 2
    end
  end
  
  #Configurazione AnsibleVM; provisioning by shell mediante script ansible.sh
  config.vm.define "AnsibleVM" do |ansible|
    ansible.vm.box_check_update = false
    ansible.vm.box = "ubuntu/xenial64"
    ansible.vm.network "forwarded_port", guest: 101, host: 1010
    ansible.vm.network "private_network", ip: "192.168.90.10"
    ansible.vm.provision "shell", path: "ansible.sh"
    ansible.vm.provider "virtualbox" do |vb2|
	vb2.name = "AnsibleVM"
	vb2.memory = 2048
        vb2.cpus = 2
    end
  end
  
  #Configurazione DevelopmentVM; provisioning by shell mediante script lamp.sh
  config.vm.define "DevelopmentVM" do |development|
    development.vm.box_check_update = false
    development.vm.box = "ubuntu/xenial64"
    development.vm.network "forwarded_port", guest: 103, host: 1030
    development.vm.network "private_network", ip: "192.168.90.30"
    development.vm.provision "shell", path: "lamp.sh"
    development.vm.provider "virtualbox" do |vb3|
	vb3.name = "DevelopmentVM"
	vb3.memory = 2048
        vb3.cpus = 2
    end
  end
  
  #Configurazione TestingVM; provisioning by shell mediante script sonar.sh
  config.vm.define "TestingVM" do |testing|
    testing.vm.box_check_update = false
    testing.vm.box = "ubuntu/xenial64"
    testing.vm.network "forwarded_port", guest: 104, host: 1040
    testing.vm.network "private_network", ip: "192.168.90.40"
    testing.vm.provision "shell", path: "sonar.sh"
    testing.vm.provider "virtualbox" do |vb4|
	vb4.name = "Test6"
	vb4.memory =4096
        vb4.cpus = 2
    end
  end
end
