---

- hosts: selenium
  remote_user: root
  sudo: yes
  tasks:
  
    - name: Create folder for reports #Creazione della cartella reports sulla TestingVM 
      file: path=/reports state=directory
      
    - name: Testing on Mozilla and Chrome browsers
      shell: python /home/selenium/suite.py  >> /reports/"report_$(date +"%Y_%m_%d_%I_%M").html"
